name: Deploy Pull Request to Test Environment

on:
  push:
    branches: [staging]

jobs:
  build_docker_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: byvoxel/user-create
          tags: |
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy_to_ec2:
    name: Deploy to EC2 Instances
    runs-on: ubuntu-latest
    needs: build_docker_image
    strategy:
      matrix:
        ec2_instance: 
          - ec2-54-157-21-157.compute-1.amazonaws.com

    steps:
      - name: Configure SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ matrix.ec2_instance }}
          username: ec2-user
          port: 22
          timeout: 120
          envs: TAG=${{ needs.build_docker_image.outputs.image_tag }}
          script: |
            set -e
            echo "Deploying image with tag: ${TAG##*:}"
            sudo docker stop user-create || true
            sudo docker rm user-create || true
            sudo docker pull $TAG
            sudo docker run -d \
              --name user-create \
              -p 3020:3020 \
              --restart unless-stopped \
              $TAG
            sudo docker system prune -af --volumes || true