name: Deploy on staging environment

on:
  push:
    branches: [staging]

jobs:
  build_docker_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        env:
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          KAFKA_BROKER: ${{ secrets.KAFKA_BROKER }}
          KAFKA_CLIENT_ID: ${{ secrets.KAFKA_CLIENT_ID }}
          KAFKA_TOPIC: ${{ secrets.KAFKA_TOPIC }}
          KAFKA_TOPIC_DELETE: ${{ secrets.KAFKA_TOPIC_DELETE }}
          KAFKAJS_NO_PARTITIONER_WARNING: ${{ secrets.KAFKAJS_NO_PARTITIONER_WARNING }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}
        run: |
          echo "HOST=${HOST}" > .env
          echo "PORT=${PORT}" >> .env
          echo "MONGO_URI=${MONGO_URI}" >> .env
          echo "KAFKA_BROKER=${KAFKA_BROKER}" >> .env
          echo "KAFKA_CLIENT_ID=${KAFKA_CLIENT_ID}" >> .env
          echo "KAFKA_TOPIC=${KAFKA_TOPIC}" >> .env
          echo "KAFKA_TOPIC_DELETE=${KAFKA_TOPIC_DELETE}" >> .env
          echo "KAFKAJS_NO_PARTITIONER_WARNING=${KAFKAJS_NO_PARTITIONER_WARNING}" >> .env
          echo "ENCRYPTION_KEY=${ENCRYPTION_KEY}" >> .env
          echo "ENCRYPTION_IV=${ENCRYPTION_IV}" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: byvoxel/user-create
          tags: |
            type=raw,value=staging
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: byvoxel/user-create:staging
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy_to_ec2:
    name: Deploy to EC2 Instances
    runs-on: ubuntu-latest
    needs: build_docker_image
    strategy:
      matrix:
        ec2_instance: 
          - ec2-44-205-35-215.compute-1.amazonaws.com

    steps:
      - name: Deploy Container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ matrix.ec2_instance }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: "120s"
          script: |
            set -e
            echo "Deploying image: byvoxel/user-create:staging"
            sudo docker stop user-create || true
            sudo docker rm user-create || true
            sudo docker pull byvoxel/user-create:staging
            sudo docker run -d \
              --name user-create \
              -p 3020:3020 \
              --restart unless-stopped \
              byvoxel/user-create:staging
            sudo docker system prune -af --volumes || true